# Generated by Django 2.0.5 on 2018-05-18 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tDept',
            fields=[
                ('DeptSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='부서코드')),
                ('DeptNo', models.CharField(max_length=20, null=True, verbose_name='부서번호')),
                ('DeptName', models.CharField(max_length=20, null=True, verbose_name='부서명')),
            ],
            options={
                'verbose_name': '부서',
                'verbose_name_plural': '01.부서',
            },
        ),
        migrations.CreateModel(
            name='tEmp',
            fields=[
                ('EmpSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='사원코드')),
                ('EmpNo', models.CharField(max_length=20, null=True, verbose_name='사원번호')),
                ('EmpName', models.CharField(max_length=20, null=True, verbose_name='사원명')),
            ],
            options={
                'verbose_name': '사원',
                'verbose_name_plural': '02.사원',
            },
        ),
        migrations.CreateModel(
            name='tEquipment',
            fields=[
                ('EquipSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='장비코드')),
                ('EquipNo', models.CharField(max_length=20, null=True, verbose_name='장비번호')),
                ('EquipName', models.CharField(max_length=20, null=True, verbose_name='장비명')),
                ('EquipType', models.CharField(max_length=20, null=True, verbose_name='장비부호')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('DeptSeq', models.ForeignKey(blank=True, db_column='DeptSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTMS.tDept', verbose_name='사용부서')),
            ],
            options={
                'verbose_name': '장비',
                'verbose_name_plural': '03.장비',
            },
        ),
        migrations.CreateModel(
            name='tServiceReq',
            fields=[
                ('ServiceReqSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='공사명령서번호')),
                ('ServiceReqNo', models.CharField(max_length=20, null=True, verbose_name='공사명령서번호')),
                ('InYMD', models.DateField(verbose_name='입고일')),
                ('ReqEmpName', models.CharField(max_length=20, null=True, verbose_name='의뢰자')),
                ('FindYM', models.DateField(verbose_name='발견일자')),
                ('ErrorArea', models.CharField(blank=True, max_length=20, null=True, verbose_name='위치')),
                ('WHLocation', models.CharField(blank=True, max_length=20, null=True, verbose_name='정비부위')),
                ('EquipSeq', models.ForeignKey(blank=True, db_column='EquipSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTMS.tEquipment', verbose_name='장비Id')),
                ('InEmpSeq', models.ForeignKey(blank=True, db_column='InEmpSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTMS.tEmp', verbose_name='입고자')),
            ],
            options={
                'verbose_name': '정비의뢰',
                'verbose_name_plural': '21.정비의뢰',
            },
        ),
        migrations.CreateModel(
            name='tServiceRlt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartYMD', models.DateField(blank=True, null=True, verbose_name='정비시작일')),
                ('EndYMD', models.DateField(blank=True, null=True, verbose_name='정비종료일')),
                ('ErrorStatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='고장상태*')),
                ('FinderWork', models.CharField(blank=True, max_length=50, null=True, verbose_name='발견자조치*')),
                ('ServiceWork', models.CharField(blank=True, max_length=50, null=True, verbose_name='수리내역*')),
                ('PreventPlan', models.CharField(blank=True, max_length=50, null=True, verbose_name='예방대책*')),
                ('Remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='기타참고사항*')),
                ('WorkResult', models.CharField(blank=True, max_length=50, null=True, verbose_name='결과내용*')),
                ('OutYMD', models.DateField(blank=True, null=True, verbose_name='출고일')),
                ('RecEmpName', models.CharField(blank=True, max_length=20, null=True, verbose_name='수령자')),
                ('ServiceReqSeq', models.ForeignKey(db_column='ServiceReqSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTMS.tServiceReq', verbose_name='정비의뢰')),
            ],
            options={
                'verbose_name': '정비결과',
                'verbose_name_plural': '22.정비결과',
            },
        ),
    ]
