# Generated by Django 2.0.5 on 2018-06-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tDept',
            fields=[
                ('DeptSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='Department Sequence')),
                ('DeptNo', models.CharField(max_length=20, null=True, verbose_name='Department No')),
                ('DeptName', models.CharField(max_length=20, null=True, verbose_name='Department Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='tEmp',
            fields=[
                ('EmpSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='Employee Sequence')),
                ('EmpNo', models.CharField(max_length=20, null=True, verbose_name='Employee No')),
                ('EmpName', models.CharField(max_length=20, null=True, verbose_name='Emplyee Name')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='tEquipment',
            fields=[
                ('EquipSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='Equipment Sequence')),
                ('EquipNo', models.CharField(max_length=20, null=True, verbose_name='Equipment No')),
                ('EquipName', models.CharField(max_length=20, null=True, verbose_name='Equipment Name')),
                ('EquipType', models.CharField(max_length=20, null=True, verbose_name='Equipment Type')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='Remark')),
                ('DeptSeq', models.ForeignKey(blank=True, db_column='DeptSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTMS.tDept', verbose_name='Use Department')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='tServiceReq',
            fields=[
                ('ServiceReqSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='Service Request Sequence')),
                ('ServiceReqNo', models.CharField(max_length=20, null=True, verbose_name='Service Request No')),
                ('InYMD', models.DateField(verbose_name='Receipt Date')),
                ('ReqEmpName', models.CharField(max_length=20, null=True, verbose_name='Request Person')),
                ('FindYM', models.DateField(verbose_name='Find Date')),
                ('ErrorArea', models.CharField(blank=True, max_length=20, null=True, verbose_name='Failure Location')),
                ('WHLocation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Warehouse Location')),
                ('EquipSeq', models.ForeignKey(blank=True, db_column='EquipSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTMS.tEquipment', verbose_name='Equipment')),
                ('InEmpSeq', models.ForeignKey(blank=True, db_column='InEmpSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTMS.tEmp', verbose_name='Receipt Employee')),
            ],
            options={
                'verbose_name': 'Maintenance Request',
                'verbose_name_plural': 'Maintenance Request',
            },
        ),
        migrations.CreateModel(
            name='tServiceRlt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartYMD', models.DateField(blank=True, null=True, verbose_name='Work start date')),
                ('EndYMD', models.DateField(blank=True, null=True, verbose_name='Work finished date')),
                ('ErrorStatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Failure Status')),
                ('FinderWork', models.CharField(blank=True, max_length=50, null=True, verbose_name='Finder Action')),
                ('ServiceWork', models.CharField(blank=True, max_length=50, null=True, verbose_name='Repair Work')),
                ('PreventPlan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Faioure Protection plan')),
                ('Remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='References')),
                ('WorkResult', models.CharField(blank=True, max_length=50, null=True, verbose_name='Work Results')),
                ('OutYMD', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('RecEmpName', models.CharField(blank=True, max_length=20, null=True, verbose_name='Recipient')),
                ('ServiceReqSeq', models.ForeignKey(db_column='ServiceReqSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTMS.tServiceReq', verbose_name='Maintenance Request')),
            ],
            options={
                'verbose_name': 'Maintenance Results',
                'verbose_name_plural': 'Maintenance Results',
            },
        ),
    ]
