# Generated by Django 2.0.5 on 2018-07-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tservicereq',
            name='ServiceReqNo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Service Request No'),
        ),
        migrations.AlterUniqueTogether(
            name='tservicereq',
            unique_together={('ServiceReqNo',)},
        ),
    ]
